name: tbpore
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "python>=3.8,<4.0"
  - just
  - ripgrep
  - poetry=1.3
  - mykrobe=0.12
  - rasusa
  - samtools=1.13
  - bcftools=1.13
  - minimap2=2.22
  - seqkit=2
  - psdm=0.1.0
